Entrega do desafio
valora-org/desafio-backend pull request #8
Opened 2021-01-26 22:21 UTC by diego-marcelino

Como combinado, PR do desafio.

2021-01-27 21:35 UTC, 1cleiton commented
Olá @diego-marcelino estamos avaliando o seu desafio e faremos questionamentos sobre algumas escolhas suas. Não se sinta ofendido nem leve para o lado pessoal, não queremos questionar certo ou errado, apenas entender a sua maneira de pensar e como você interpretou cada requisito do desafio.
Abraços!

2021-01-27 21:47 UTC, diego-marcelino commented
@1cleiton  sinta-se a vontade para questionar o que desejar, fico a disposição para conversarmos a respeito.

Abraço!

2021-01-27 22:57 UTC, 1cleiton requested changes
@diego-marcelino Fiz alguns comentários na avaliação. Não precisa se preocupar em alterar nada no código, é apenas para entendermos o porquê das suas escolhas.

2021-01-27 22:57 UTC, 1cleiton commented on quiz/ranking/views.py
> +        return profile.general_score
@diego-marcelino Porque você optou por implementar o sort e o filter manualmente e não utilizar o Filter e SearchFilter do próprio django-rest-framework?

2021-01-27 23:09 UTC, diego-marcelino commented on quiz/ranking/views.py
> +        return profile.general_score
@1cleiton esses recursos fazem uso de querysets e por isso os atributos devem ser campos no banco de dados, e nesses casos são properties. Tentei utilizar esses recursos, assim como 'ordering' nos serializers e 'ordering_fields' no viewset, e por isso optei por essa solução.

2021-01-27 23:17 UTC, diego-marcelino commented on quiz/questions/models.py
> +        null=False, validators=[MaxValueValidator(2)])
As alternativas são salvas em um array assim como o índice da alternativa correta.

2021-01-27 23:19 UTC, diego-marcelino commented on quiz/match/serializers.py
> +            match.save()
Durante os meus testes o objeto não estava persistindo no db, por isso utilizei o save.

2021-01-27 23:27 UTC, lfvilella reviewed
@diego-marcelino Fiquei curioso para saber qual foi o motivo de ter escolhido o `django cookiecutter`, como ele funciona e quais são os benefícios que ele traz?

2021-01-27 23:27 UTC, lfvilella commented on quiz/core/viewmixins.py
> +from .permissions import IsPlayer
@diego-marcelino Eu gosto de utilizar a importação de módulos assim da uma minimizada e fica mais clean para ler e ajuda em futuros refactors, pois assim sabemos de onde está vindo determinado objeto. Por exemplo:
`from . import permissions` e usaria `permissions.IsAdmin`.

Curiosidade: [pep-8 imports](https://www.python.org/dev/peps/pep-0008/#imports)

2021-01-27 23:27 UTC, lfvilella commented on quiz/ranking/tests/test_views.py
> +import pytest
@diego-marcelino Você testou o cenário de dois usuários jogando o quiz ?

Por exemplo, temos o `user1` e o `user2`, ambos jogando o mesmo quiz, mas o user2 acertou mais questões e consequentemente fez mais pontos e então estaria no `top1`.

2021-01-27 23:33 UTC, diego-marcelino commented on quiz/core/viewmixins.py
> +from .permissions import IsPlayer
Concordo. Meu raciocício é: com poucos objetos importados menciono um por vez, se muitos forem necessários importo o módulo todo.

2021-01-27 23:35 UTC, diego-marcelino commented on quiz/ranking/tests/test_views.py
> +import pytest
Sim, testei com 2 usuários, mas não com mais de 2 que seria o ideal. Nos testes que fiz funcionou como esperado.

2021-01-27 23:56 UTC, diego-marcelino commented
> @diego-marcelino Fiquei curioso para saber qual foi o motivo de ter escolhido o `django cookiecutter`, como ele funciona e quais são os benefícios que ele traz?

@lfvilella O Cookiecutter é um utilitário para criar novos projetos através de templates, há templates para diversos tipos de projetos em diferentes linguagens e diversas opções de personalização. Como citado no readme, o Django Cookiecutter é recomendado nos livros que citei. Utilizando o Django Cookiecutter já consegui um bootstrap do projeto com as configurações do Docker, arquivos de settings e requirements divididos em local, testes e produção, pre-commit, pytest, Heroku, whitenoise, CI do Github, além de opções que não selecionei no setup como email, Celery, task runner pra javascript, etc.

2021-01-28 14:41 UTC, 1cleiton commented
@diego-marcelino Obrigado pelas respostas e pela sua disponibilidade em participar do nosso processo seletivo. Já finalizamos a sua revisão e em breve você receberá o resultado através do recrutador responsável pelo seu processo.
Abraço!

2021-01-28 14:41 UTC, closed without merging